version: 2
jobs:
  build-and-test:
    docker:
      - image: naftulikay/circleci-rust:latest
    steps:
      - checkout
      - run:
          name: Running tests
          command: cargo test
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
