version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/rust:1.28.0-stretch-node
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            cargo install cargo-test-junit
            mkdir -p test-output
            cargo test-junit --name test-output/output.xml
      - store_test_results:
          path: test-output
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
