[package]
name = "parinfer"
version = "0.1.0"
authors = ["Jason Felice <jason.m.felice@gmail.com>"]

[features]
unstable = []

[dev-dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
